Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2021-05, with the labels that each got.

#23 Issue #17 - Refactor code from "utils.js" (and add ESLint)
  .eslintrc.json
  package.json
  src/background.js
  src/js/migration.js
  src/js/options.js
  src/js/postHandler.js
  src/js/shared/config_file.js
  src/js/shared/constants.js
  src/js/shared/local_store.js
  src/js/shared/misc.js
  src/js/shared/provider_helper.js
  src/js/shared/storage.js
  src/js/utils.js
  yarn.lock
Labels: qa complete

#31 Issue #30 - Enable 'split chunks' on Webpack for prevent duplicated code
  webpack.config.js
Labels: qa complete, ready-for-review

#34 Bug/20 focus options tab if opened
  src/background.js
Labels: code-reviewed, qa-complete

#37 Merge 'main' into 'develop'
  src/background.js
Labels: qa-complete

#38 Issue #30 - Split entry files into chunks (except for the background file)
  package.json
  src/migration.html
  src/options.html
  src/postHandler.html
  src/views/settings.html
  webpack.config.js
  yarn.lock
Labels: qa-complete

#41 Enhancement/40 re enable lint rules
  .eslintrc.json
  src/js/migration.js
  src/js/options.js
  src/js/shared/local_store.js
Labels: code-reviewed, qa-complete, question

#42 Enhancement/32 make urls constant
  src/js/options.js
  src/js/shared/constants.js
  src/options.html
  src/views/providers.html
Labels: qa-complete, ready-for-review

#43 Gray out disable groups instead of line-through
  src/js/options.js
Labels: code-reviewed, qa-complete

#27 Issue #5 | Add import, export and edit functionality in Settings TAB
  .prettierrc.json
  package.json
  src/js/options.js
  src/js/shared/constants.js
  src/views/settings.html
  yarn.lock
Labels: code-reviewed, qa-complete

#48 Add icon with buttons
  src/options.html
  src/views/providers.html
  src/views/settings.html
Labels: code-reviewed, qa-complete
