Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2021-06, with the labels that each got.

#50 Enhancement/15 use aesjs
  package.json
  src/js/shared/config_file.js
  src/js/shared/encryption.js
  yarn.lock
Labels: qa-complete, ready-for-review

#51 Feature #11 - Command to zip dist folder
  .gitignore
  README.md
  package.json
  yarn.lock
Labels: ready-for-review

#52 Issue #10 - Use Prettier to format HTML, CSS and JSON files
  .eslintrc.json
  .prettierrc.json
  README.md
  package.json
  src/css/main.css
  src/manifest.json
  src/migration.html
  src/postHandler.html
  src/views/settings.html
  yarn.lock
Labels: code-reviewed, qa-complete

#49 Issue #6 | Add additional settings
  .gitignore
  src/js/migration.js
  src/js/options.js
  src/js/shared/config_file.js
  src/js/shared/constants.js
  src/views/settings.html
Labels: qa-complete, ready-for-review

#56 Issue #6 - Initialize new options when parsing a Configuration File
  src/js/shared/config_file.js
Labels: code-reviewed, qa-complete
