Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2021-07, with the labels that each got.

#55 Issue #7 | Add Mixpanel
  .eslintrc.json
  README.md
  dev.env
  package.json
  prod.env
  src/background.js
  src/js/shared/analytics.js
  src/js/shared/constants.js
  webpack.config.js
  yarn.lock
Labels: qa-complete, ready-for-review

#60 Issue #54 - Allow to update URLs and Labels from Search Providers
  package.json
  src/js/migration.js
  src/js/shared/config_file.js
  src/js/shared/constants.js
Labels: code-reviewed, qa-complete

#53 Issue #22 | Fix branding
  settings.json
Labels: code-reviewed, qa-complete

#62 Feature/58 add unit testing
  .eslintrc.json
  README.md
  babel.config.json
  jest.config.js
  package.json
  src/background.js
  tests/unit/background.spec.js
  yarn.lock
Labels: code-reviewed, qa-complete

#61 Feature #59 - Add E2E tests
  .eslintrc.json
  .gitignore
  jest.config.js
  package.json
  src/views/providers.html
  tests/e2e/options.spec.js
  tests/e2e/util.js
  yarn.lock
Labels: code-reviewed, qa-complete

#72 Enhancement/63 unit test for update now
  jest.config.js
  package.json
  tests/resources/defaultSettings.json
  tests/resources/encryptedSettings.json
  tests/unit/background.spec.js
  tests/unit/configFile.spec.js
  tests/unit/util.js
  yarn.lock
Labels: code-reviewed, qa-complete

#71 Enhancement/65 migration e2e test
  package.json
  tests/e2e/migration.spec.js
  tests/e2e/options.spec.js
  tests/e2e/util.js
Labels: qa-complete, ready-for-review

#74 Enhancement/64 test generate json file
  src/js/shared/config_file.js
  tests/resources/defaultSettings.json
  tests/unit/configFile.spec.js
Labels: qa-complete, ready-for-review

#75 Issue #4 - Custom Bootstrap theming
  package.json
  src/js/migration.js
  src/js/options.js
  src/js/postHandler.js
  src/styles/theme.scss
  webpack.config.js
  yarn.lock
Labels: code-reviewed, qa-complete

#79 Issue #67 - Add unit tests for sanitizeSettings
  src/js/shared/config_file.js
  tests/unit/configFile.spec.js
Labels: needs-qa, ready-for-review
