Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2021-11, with the labels that each got.

#108 Issue #107 - Migrate Post Handler from Mustache to Svelte
  .prettierrc.json
  README.md
  jest.config.js
  package.json
  src/background.js
  src/components/postHandler.svelte
  src/js/postHandler.js
  src/js/shared/config_file.js
  src/js/shared/encryption.js
  src/postHandler.html
  tests/e2e/options.spec.js
  tests/resources/encryptedSettings.json
  tests/unit/background.spec.js
  tests/unit/configFile.spec.js
  tests/unit/contextMenu.spec.js
  tests/unit/encryption.spec.js
  tests/unit/util.js
  webpack.config.js
  yarn.lock
Labels: qa-complete, code-reviewed

#111 Issue #110 - Implement component for Options' footer
  src/components/options/footer.svelte
  src/js/options.js
  src/options.html
  tests/e2e/options.spec.js
Labels: qa-complete, code-reviewed

#118 Issue #120 - fix eslint error
  .eslintrc.json
  package.json
  yarn.lock
Labels: ready-for-review, needs-qa

#124 Issue #123 | Remove mixpanel related code (master)
  dev.env
  edge.env
  package.json
  prod.env
  src/background.js
  src/js/shared/analytics.js
  src/js/shared/constants.js
  webpack.config.js
  yarn.lock
Labels: high-priority, qa-complete, code-reviewed

#125 Issue #123 | Remove mixpanel related code (develop)
  dev.env
  edge.env
  package.json
  prod.env
  src/background.js
  src/js/shared/analytics.js
  src/js/shared/constants.js
  webpack.config.js
  yarn.lock
Labels: qa-complete, code-reviewed

#121 Issue #113 - refactor import export section
  src/components/options/header.svelte
  src/components/options/settings/importExport.svelte
  src/js/options.js
  src/views/settings.html
Labels: ready-for-review, qa-complete

#127 Issue #115 - Merge options component
  src/components/options/settings/importExport.svelte
  src/components/shared/field.svelte
  src/components/shared/fields.svelte
  src/js/options.js
  src/js/shared/constants.js
  src/views/settings.html
Labels: qa-complete, code-reviewed

#128 Issue #116 - Implement component for "Search results" section
  src/js/options.js
  src/views/settings.html
Labels: ready-for-review, qa-complete
