Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2021-09, with the labels that each got.

#99 Issue #87 - implement encrypt function
  jest.config.js
  src/js/shared/encryption.js
  tests/resources/encryptedSettings.json
  tests/unit/encryption.spec.js
  tests/unit/util.js
Labels: ready-for-review, qa-complete

#102 Issue #89 - Add unit test for onAlarm listener
  src/background.js
  tests/unit/background.spec.js
Labels: needs-qa, code-reviewed

#100 Issue #94 - improve how groups name is imported
  src/js/shared/config_file.js
  tests/unit/configFile.spec.js
Labels: ready-for-review, qa-complete

#103 Issue #90 - test search result options
  tests/unit/contextMenu.spec.js
Labels: ready-for-review, needs-qa

#105 Issue PIX-311 - e2e test for example link
  tests/e2e/options.spec.js
Labels: ready-for-review, qa-complete
