Repository AdvancedThreatAnalytics/threat-analytics-search, pull requests merged in 2022-03, with the labels that each got.

#170 Issue #169 | Validate Groups at start
  src/components/options/providers/groups.svelte
Labels: ready-for-review, qa-complete

#171 Issue #158 - Improve validation on Queries inputs
  src/components/options/special/queries.svelte
Labels: ready-for-review, qa-complete

#175 Issue #174 | Show warning if Link/Query does not contains TESTSEARCH
  src/components/options/providers/add.svelte
  src/components/options/providers/contextMenuItems.svelte
  src/components/options/special/queries.svelte
  src/js/shared/misc.js
Labels: ready-for-review, high-priority, qa-complete

#178 Issue #177 | Do not show warning if query/link is searchable
  src/components/options/providers/contextMenuItems.svelte
  src/components/options/special/queries.svelte
Labels: high-priority, qa-complete, review-complete

#182 Issue #179 - Fix E2E test for check search providers order
  src/components/options/providers/contextMenuItems.svelte
Labels: ready-for-review, qa-complete

#181 Issue #180 | Move puppeteer to dev dependency
  package.json
Labels: qa-complete, review-complete

#186 pix-1010 #183 - clarify when MSO is used
  src/components/options/providers/contextMenuItems.svelte
  src/components/options/settings/importExport.svelte
  src/components/options/settings/main.svelte
Labels: ready-for-review, qa-complete

#185 Issue #184 | Update special providers data when importing configurati…
  src/components/options/main.svelte
  src/components/options/special/main.svelte
  src/components/options/special/queries.svelte
  src/components/options/special/settings.svelte
Labels: qa-complete, review-complete
